### ISSUE TITLE
Docker image: cannot find module 'express'

### ISSUE THREAD

**Issue by tuckerconnelly** [andersonba/puppeteer-assets#1]
Looks like something is up with the docker image not having express installed. Logs:

```
prometheus-assets_1  | module.js:540
prometheus-assets_1  |     throw err;
prometheus-assets_1  |     ^
prometheus-assets_1  |
prometheus-assets_1  | Error: Cannot find module 'express'
prometheus-assets_1  |     at Function.Module._resolveFilename (module.js:538:15)
prometheus-assets_1  |     at Function.Module._load (module.js:468:25)
prometheus-assets_1  |     at Module.require (module.js:587:17)
prometheus-assets_1  |     at require (internal/module.js:11:18)
prometheus-assets_1  |     at Object.<anonymous> (/app/prometheus/index.js:2:17)
prometheus-assets_1  |     at Module._compile (module.js:643:30)
prometheus-assets_1  |     at Object.Module._extensions..js (module.js:654:10)
prometheus-assets_1  |     at Module.load (module.js:556:32)
prometheus-assets_1  |     at tryModuleLoad (module.js:499:12)
prometheus-assets_1  |     at Function.Module._load (module.js:491:3)
prometheus-assets_1  | error Command failed with exit code 1.
prometheus-assets_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rometheus-assets_1 exited with code 1
```

**Comment by andersonba** [comment]
weird 🤔 
I just run on my computer and it is working properly.
I'm releasing a new version, anyway, thanks for your contribution.
